name: runtime
description: A simple command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  alfred: ^0.1.4+5
  appwrite_function_types:
    path: ./appwrite_function_types/
  shelf: ^1.2.0

dev_dependencies:
  pedantic: ^1.10.0
